DROP TABLE IF EXISTS "AnimalSounds";
CREATE TABLE "AnimalSounds" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "UID" TEXT, "SOUNDEFFECTNAME" TEXT, "FAVSTATUS" INTEGER DEFAULT 0);
INSERT INTO "AnimalSounds" VALUES(1,'ASC000','Crickets Chirping',0);
INSERT INTO "AnimalSounds" VALUES(2,'ASC001','Dolphin',0);
INSERT INTO "AnimalSounds" VALUES(3,'ASC002','Meep Meep',0);
INSERT INTO "AnimalSounds" VALUES(4,'ASC003','Snake Hissing',0);
DROP TABLE IF EXISTS "FartSounds";
CREATE TABLE "FartSounds" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "UID" TEXT, "SOUNDEFFECTNAME" TEXT, "FAVSTATUS" INTEGER DEFAULT 0);
INSERT INTO "FartSounds" VALUES(1,'FSC000','Burp',0);
INSERT INTO "FartSounds" VALUES(2,'FSC001','Fart #1',0);
INSERT INTO "FartSounds" VALUES(3,'FSC002','Fart #2',0);
INSERT INTO "FartSounds" VALUES(4,'FSC003','Fart #3',0);
DROP TABLE IF EXISTS "HumanSounds";
CREATE TABLE "HumanSounds" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "UID" TEXT, "SOUNDEFFECTNAME" TEXT, "FAVSTATUS" INTEGER DEFAULT 0);
INSERT INTO "HumanSounds" VALUES(1,'HSC000','Aint nobody got the time for that',0);
INSERT INTO "HumanSounds" VALUES(2,'HSC001','Arnold:i will be back',0);
INSERT INTO "HumanSounds" VALUES(3,'HSC002','Awww',0);
INSERT INTO "HumanSounds" VALUES(4,'HSC003','Bye, have a great time',0);
INSERT INTO "HumanSounds" VALUES(5,'HSC004','Cartoon laugh',0);
INSERT INTO "HumanSounds" VALUES(6,'HSC005','COD shouting',0);
INSERT INTO "HumanSounds" VALUES(7,'HSC006','COD zombies kaBOOM',0);
INSERT INTO "HumanSounds" VALUES(8,'HSC007','Crowd cheering',0);
INSERT INTO "HumanSounds" VALUES(9,'HSC008','Denied',0);
INSERT INTO "HumanSounds" VALUES(10,'HSC009','Derp yell',0);
INSERT INTO "HumanSounds" VALUES(11,'HSC010','D''oh #1',0);
INSERT INTO "HumanSounds" VALUES(12,'HSC011','D''oh #2',0);
INSERT INTO "HumanSounds" VALUES(13,'HSC012','Dr.Zoidberg woop',0);
INSERT INTO "HumanSounds" VALUES(14,'HSC013','Everybody put your hands in the air',0);
INSERT INTO "HumanSounds" VALUES(15,'HSC014','Evil laugh',0);
INSERT INTO "HumanSounds" VALUES(16,'HSC015','Frag out',0);
INSERT INTO "HumanSounds" VALUES(17,'HSC016','FUS RO DAH',0);
INSERT INTO "HumanSounds" VALUES(18,'HSC017','Get no scoped',0);
INSERT INTO "HumanSounds" VALUES(19,'HSC018','Get over here',0);
INSERT INTO "HumanSounds" VALUES(20,'HSC019','Gibberish',0);
INSERT INTO "HumanSounds" VALUES(21,'HSC020','Ha gay',0);
INSERT INTO "HumanSounds" VALUES(22,'HSC021','Ha got emm',0);
INSERT INTO "HumanSounds" VALUES(23,'HSC022','Ha Ha (Nelson)',0);
INSERT INTO "HumanSounds" VALUES(24,'HSC023','Heart beat',0);
INSERT INTO "HumanSounds" VALUES(25,'HSC024','Hello cutie pie',0);
INSERT INTO "HumanSounds" VALUES(26,'HSC025','I got a bad feeling about this(Han Solo)',0);
INSERT INTO "HumanSounds" VALUES(27,'HSC026','Kill shot',0);
INSERT INTO "HumanSounds" VALUES(28,'HSC027','Kobe',0);
INSERT INTO "HumanSounds" VALUES(29,'HSC028','Look at this dude Lauging',0);
INSERT INTO "HumanSounds" VALUES(30,'HSC029','Mario here we go',0);
INSERT INTO "HumanSounds" VALUES(31,'HSC030','Nope',0);
INSERT INTO "HumanSounds" VALUES(32,'HSC031','Oh hell no',0);
INSERT INTO "HumanSounds" VALUES(33,'HSC032','OMG who the hell cares',0);
INSERT INTO "HumanSounds" VALUES(34,'HSC033','Quad',0);
INSERT INTO "HumanSounds" VALUES(35,'HSC034','Say what',0);
INSERT INTO "HumanSounds" VALUES(36,'HSC035','Scream',0);
INSERT INTO "HumanSounds" VALUES(37,'HSC036','Spongebob time card:A few inches later',0);
INSERT INTO "HumanSounds" VALUES(38,'HSC037','Spongebob time card:A few moments later',0);
INSERT INTO "HumanSounds" VALUES(39,'HSC038','Spongebob time card:Eventually',0);
INSERT INTO "HumanSounds" VALUES(40,'HSC039','Spongebob time card:Meanwhile',0);
INSERT INTO "HumanSounds" VALUES(41,'HSC040','Spongebob time card:One eternity later',0);
INSERT INTO "HumanSounds" VALUES(42,'HSC041','Spongebob time card:Uhh',0);
INSERT INTO "HumanSounds" VALUES(43,'HSC042','Super hot fire OHHH',0);
INSERT INTO "HumanSounds" VALUES(44,'HSC043','Tango down',0);
INSERT INTO "HumanSounds" VALUES(45,'HSC044','Target neutralized',0);
INSERT INTO "HumanSounds" VALUES(46,'HSC045','They ask you how you are',0);
INSERT INTO "HumanSounds" VALUES(47,'HSC046','To infinty and beyond',0);
INSERT INTO "HumanSounds" VALUES(48,'HSC047','Toasty',0);
INSERT INTO "HumanSounds" VALUES(49,'HSC048','What a joker laugh',0);
INSERT INTO "HumanSounds" VALUES(50,'HSC049','Yay',0);
INSERT INTO "HumanSounds" VALUES(51,'HSC050','You suck You jackass',0);
INSERT INTO "HumanSounds" VALUES(52,'HSC051','You suck',0);
INSERT INTO "HumanSounds" VALUES(53,'HSC052','You are the last one, Complete the mission',0);
INSERT INTO "HumanSounds" VALUES(54,'HSC053','Zach Galifianakis laugh',0);
INSERT INTO "HumanSounds" VALUES(55,'HSC054','Hey what happened',0);
INSERT INTO "HumanSounds" VALUES(56,'HSC055','Monster Kill',0);
DROP TABLE IF EXISTS "MusicClips";
CREATE TABLE "MusicClips" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "UID" TEXT, "SOUNDEFFECTNAME" TEXT, "FAVSTATUS" INTEGER DEFAULT 0);
INSERT INTO "MusicClips" VALUES(1,'MSC000','Boxing gloves by Julio Kladniew',0);
INSERT INTO "MusicClips" VALUES(2,'MSC001','Epic choir suspense',0);
INSERT INTO "MusicClips" VALUES(3,'MSC002','Fail - WHAA WHAA WHAA Version',0);
INSERT INTO "MusicClips" VALUES(4,'MSC003','Heavenly choir',0);
INSERT INTO "MusicClips" VALUES(5,'MSC004','Hidden Masters theme',0);
INSERT INTO "MusicClips" VALUES(6,'MSC005','Illuminati',0);
INSERT INTO "MusicClips" VALUES(7,'MSC006','Intro sound effect',0);
INSERT INTO "MusicClips" VALUES(8,'MSC007','Kevin Mcleod: Fluffing a duck',0);
INSERT INTO "MusicClips" VALUES(9,'MSC008','Kevin Mcleod: Monkeys spinning Monkeys',0);
INSERT INTO "MusicClips" VALUES(10,'MSC009','Kevin MacLeod: Scheming Weasel',0);
INSERT INTO "MusicClips" VALUES(11,'MSC010','Kevin Macleod: The Builder',0);
INSERT INTO "MusicClips" VALUES(12,'MSC011','Kevin Macleod: Hidden agenda',0);
INSERT INTO "MusicClips" VALUES(13,'MSC012','Kevin Macleod: Investigations',0);
INSERT INTO "MusicClips" VALUES(14,'MSC013','Kevin Macleod: Movement proposition',0);
INSERT INTO "MusicClips" VALUES(15,'MSC014','Kevin Macleod: Sneaky snitch',0);
INSERT INTO "MusicClips" VALUES(16,'MSC015','Sad Music #1',0);
INSERT INTO "MusicClips" VALUES(17,'MSC016','Sad Music #2',0);
INSERT INTO "MusicClips" VALUES(18,'MSC017','Victory',0);
INSERT INTO "MusicClips" VALUES(19,'MSC018','Y u always lying',0);
DROP TABLE IF EXISTS "SoundEffects";
CREATE TABLE "SoundEffects" ("ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "UID" TEXT, "SOUNDEFFECTNAME" TEXT, "FAVSTATUS" INTEGER DEFAULT 0);
INSERT INTO "SoundEffects" VALUES(1,'SESC000','Ba dum tss',0);
INSERT INTO "SoundEffects" VALUES(2,'SESC001','Ballista slo-mo',0);
INSERT INTO "SoundEffects" VALUES(3,'SESC002','Barrett 50 CAL slo-mo',0);
INSERT INTO "SoundEffects" VALUES(4,'SESC003','Barrett 50 CAL',0);
INSERT INTO "SoundEffects" VALUES(5,'SESC004','Boom swoosh',0);
INSERT INTO "SoundEffects" VALUES(6,'SESC005','Boom',0);
INSERT INTO "SoundEffects" VALUES(7,'SESC006','Buzzer - Wrong answer',0);
INSERT INTO "SoundEffects" VALUES(8,'SESC007','Camera shutter #1',0);
INSERT INTO "SoundEffects" VALUES(9,'SESC008','Camera shutter #2',0);
INSERT INTO "SoundEffects" VALUES(10,'SESC009','Car Crash',0);
INSERT INTO "SoundEffects" VALUES(11,'SESC010','Car horn',0);
INSERT INTO "SoundEffects" VALUES(12,'SESC011','Cartoon boing #1',0);
INSERT INTO "SoundEffects" VALUES(13,'SESC012','Cartoon boing #2',0);
INSERT INTO "SoundEffects" VALUES(14,'SESC013','Cartoon boing #3',0);
INSERT INTO "SoundEffects" VALUES(15,'SESC014','Cartoon clock',0);
INSERT INTO "SoundEffects" VALUES(16,'SESC015','Cartoon pop',0);
INSERT INTO "SoundEffects" VALUES(17,'SESC016','Cartoon ricochet #1',0);
INSERT INTO "SoundEffects" VALUES(18,'SESC017','Cartoon ricochet #2',0);
INSERT INTO "SoundEffects" VALUES(19,'SESC018','Cartoon spin',0);
INSERT INTO "SoundEffects" VALUES(20,'SESC019','Cartoon taunt',0);
INSERT INTO "SoundEffects" VALUES(21,'SESC020','Cartoon tire screech',0);
INSERT INTO "SoundEffects" VALUES(22,'SESC021','Cartoon transition',0);
INSERT INTO "SoundEffects" VALUES(23,'SESC022','Censor beep',0);
INSERT INTO "SoundEffects" VALUES(24,'SESC023','Swoosh - Dramatic ',0);
INSERT INTO "SoundEffects" VALUES(25,'SESC024','Denied',0);
INSERT INTO "SoundEffects" VALUES(26,'SESC025','Drum roll',0);
INSERT INTO "SoundEffects" VALUES(27,'SESC026','DSR slo-mo',0);
INSERT INTO "SoundEffects" VALUES(28,'SESC027','DUN DUN DUNN',0);
INSERT INTO "SoundEffects" VALUES(29,'SESC028','Eat or munch #1',0);
INSERT INTO "SoundEffects" VALUES(30,'SESC029','Eat or munch #2',0);
INSERT INTO "SoundEffects" VALUES(31,'SESC030','Explosion #1',0);
INSERT INTO "SoundEffects" VALUES(32,'SESC031','Explosion #2',0);
INSERT INTO "SoundEffects" VALUES(33,'SESC032','Fail #1',0);
INSERT INTO "SoundEffects" VALUES(34,'SESC033','Fail #2',0);
INSERT INTO "SoundEffects" VALUES(35,'SESC034','Falling',0);
INSERT INTO "SoundEffects" VALUES(36,'SESC035','Fast tip-toes',0);
INSERT INTO "SoundEffects" VALUES(37,'SESC036','Monster kill',0);
INSERT INTO "SoundEffects" VALUES(38,'SESC037','Inception Fog Horn',0);
INSERT INTO "SoundEffects" VALUES(39,'SESC038','Kick',0);
INSERT INTO "SoundEffects" VALUES(40,'SESC039','LightSaber #1',0);
INSERT INTO "SoundEffects" VALUES(41,'SESC040','LightSaber #2',0);
INSERT INTO "SoundEffects" VALUES(42,'SESC041','M40A3',0);
INSERT INTO "SoundEffects" VALUES(43,'SESC042','Mario jump',0);
INSERT INTO "SoundEffects" VALUES(44,'SESC043','MGS Alert',0);
INSERT INTO "SoundEffects" VALUES(45,'SESC044','MLG Horns',0);
INSERT INTO "SoundEffects" VALUES(46,'SESC045','Punch #1',0);
INSERT INTO "SoundEffects" VALUES(47,'SESC046','Punch #2',0);
INSERT INTO "SoundEffects" VALUES(48,'SESC047','Punch #3',0);
INSERT INTO "SoundEffects" VALUES(49,'SESC048','Punch #4',0);
INSERT INTO "SoundEffects" VALUES(50,'SESC049','Record Rewind',0);
INSERT INTO "SoundEffects" VALUES(51,'SESC050','Record Scratch #1',0);
INSERT INTO "SoundEffects" VALUES(52,'SESC051','Record Scratch #2',0);
INSERT INTO "SoundEffects" VALUES(53,'SESC052','Reloading',0);
INSERT INTO "SoundEffects" VALUES(54,'SESC053','Rubber Duck #1',0);
INSERT INTO "SoundEffects" VALUES(55,'SESC054','Rubber Duck #2',0);
INSERT INTO "SoundEffects" VALUES(56,'SESC055','Scrambling - FlintStone',0);
INSERT INTO "SoundEffects" VALUES(57,'SESC056','Slide up',0);
INSERT INTO "SoundEffects" VALUES(58,'SESC057','Slip',0);
INSERT INTO "SoundEffects" VALUES(59,'SESC058','Splat',0);
INSERT INTO "SoundEffects" VALUES(60,'SESC059','Sudden suspense #1',0);
INSERT INTO "SoundEffects" VALUES(61,'SESC060','Sudden suspense #2',0);
INSERT INTO "SoundEffects" VALUES(62,'SESC061','Sudden suspense #3',0);
INSERT INTO "SoundEffects" VALUES(63,'SESC062','Suspense #1',0);
INSERT INTO "SoundEffects" VALUES(64,'SESC063','Suspense #2',0);
INSERT INTO "SoundEffects" VALUES(65,'SESC064','Suspense #3',0);
INSERT INTO "SoundEffects" VALUES(66,'SESC065','Suspense #4',0);
INSERT INTO "SoundEffects" VALUES(67,'SESC066','Swoosh #1',0);
INSERT INTO "SoundEffects" VALUES(68,'SESC067','Swoosh #2',0);
INSERT INTO "SoundEffects" VALUES(69,'SESC068','Swoosh #3',0);
INSERT INTO "SoundEffects" VALUES(70,'SESC069','Swoosh #4',0);
INSERT INTO "SoundEffects" VALUES(71,'SESC070','Swoosh #5',0);
INSERT INTO "SoundEffects" VALUES(72,'SESC071','Throwing Knife hitmaker',0);
INSERT INTO "SoundEffects" VALUES(73,'SESC072','Throwing',0);
INSERT INTO "SoundEffects" VALUES(74,'SESC073','Tip Toe - Cartoon Xylophone',0);
INSERT INTO "SoundEffects" VALUES(75,'SESC074','Tomahawk hitmaker',0);
INSERT INTO "SoundEffects" VALUES(76,'SESC075','Tv static',0);
INSERT INTO "SoundEffects" VALUES(77,'SESC076','Vine Gun shot',0);
